GET https://sheet2api.com/v1/G8m99f5BQ0uj/sheet-to-api/data-sheet

###
POST https://sheet2api.com/v1/G8m99f5BQ0uj/sheet-to-api/data-sheet
content-type: application/json

{
    "Date": "8/19/2020",
    "High": 125.543622,
    "Low": 237.342658,
    "Volume": 544.002627
  }

###
DELETE https://sheet2api.com/v1/G8m99f5BQ0uj/sheet-to-api/data-sheet